- data-collector/serverless.yml
- Moves function VPC config to correct section of serverless.yml
- Adds additional IAM Role permissions to correctly execute in a VPC
- Previous configuration would not deploy to a VPC, which is misleading given the configuration
> data-collector: Fixed serverless config for VPC

- Cargo.lock
- data-collector/Cargo.toml
- The branch dependency for Kiln_lib in data-collector
- Fixes the broken build
> Meta: Fix dependency on kiln_lib referring to a deleted branch

- .github/ISSUE_TEMPLATE/documentation.md
- Adds documentation issue template
- Closes #50 
- Makes it easy for users to raise issues with documentation and capture the relevant information
> Meta: Added documentation issue template

- data-collector/Cargo.lock
- Updates Cargo.lock to remove remaining dependencies on lambda crates and serverless framework
- Closes #47 
> Data-collector: Removing last dependencies on serverless

- kiln_lib/src/lib.rs
Implementation of TryFrom traits for OutputFormat and Environment and refactoring code.
It unblocks the work for the data forwarder #15 
> Kiln lib try from impl

- kiln_lib/src/lib.rs
Adds a missing field to a validation error
Fixes failing CI
> kiln_lib: Fix missing JSON field name in validation error

- kiln_lib/src/lib.rs
Adds display and error implementations for ValidationError
Allows us to return multiple error types in consuming code
> Adding a display and error implementation for ValidationError

- .github/workflows/continuous-integration-workflow.yml
Reverts simplybusiness/Kiln#75
> Revert "CI: Cargo caching"

- .github/labeler.yml
* Updated PR Labelling config
* To make it clear when a PR affects the data-forwarder component
> CI: Add PR labelling for data-forwarder related PRs

- .github/labeler.yml
- .github/workflows/continuous-integration-workflow.yml
- .gitignore
- Makefile.toml
- data-collector/Makefile.toml
- data-forwarder/Makefile.toml
- docs/integration_testing.md
- tool-images/ruby/bundler-audit/Dockerfile
- tool-images/ruby/bundler-audit/Makefile.toml
- tool-images/ruby/bundler-audit/entrypoint.sh
This PR adds support for the Bundler-audit tool
Closes #17 
> Tool: Bundler audit

- .github/workflows/build-docker-images.yml
- Changes the docker image push targets in master ci
- Fixes build required for #44
> CI: Make sure docker build targets for pushing images are correct

- data-collector/Cargo.lock
- data-collector/Cargo.toml
- data-collector/src/main.rs
- Deletes logic that now lives in kiln_lib::kafka
-  Avoids duplication of logic (for upcoming #61)
> Refactor kafka connection data collector

- kiln_lib/Cargo.lock
- kiln_lib/Cargo.toml
- kiln_lib/src/avro_schema.rs
- kiln_lib/src/dependency_event.rs
- kiln_lib/src/lib.rs
- kiln_lib/src/validation.rs
- Adds the DependencyEvent struct
- Adds corresponding Avro schema
- Adds logic to go from struct <-> Avro
- Required for #61
> Kiln_lib: Dependency events

- docs/integration_testing.md
- report-parser/Cargo.lock
- report-parser/Cargo.toml
- report-parser/src/main.rs
- Consumes ToolReports from Kafka, parse out a collection of DependencyEvents, then publish to DependencyEvents Kafka topic
> Dependency event creation

- report-parser/src/main.rs
- Stops storing the whole parsed CVE info from the NIST NVD, instead only storing CVSS score in a hashmap keyed on CVE ID
- Reduces observed memory usage from 4.3GB to 46MB, with spikes of a few hundred megabytes during data decompression
> Report-parser: Massively reduce memory usage by only storing CVE info that we need

- docs/integration_testing.md
- Updates integration testing documentation to include slack-connector component
- Minor typographical changes
- Keeps testing documentation accurate to make testing easier
> Docs: Update integration testing docs to include slack connector

- CODE_OF_CONDUCT.md
The CoC
As requested by Simply Business Legal. 
- [ X] Tests added/updated as appropriate
- [ X] Documentation added/updated as appropriate
> Update CoC after a request from Legal

- report-parser/README.md
- slack-connector/README.md
#What does this PR change?
- Adds a note to the README files for report-parser and slack-connector about bug #139.
- TO make sure users don't have a negative experience and spend time troubleshooting a known issue while it is being investigated and fixed.
> Docs: Update READMEs for Slack-connector and Report-parser to include note about bug #14

- README.md
- Fixes a typo in the project README.md
- Documentation quality
> Docs: Fix typo in readme

- data-collector/src/main.rs
- Fixes an issue where the Kafka FutureProducer was not starting the internal thread, leading to messages not being produced
- Fixes the Data-collector not producing messages
> Data-collector: Fix messages not being produced to Kafka

- .github/labeler.yml
Ensures that PRs that affect the CLI component are appropriately labelled
PR scope clarity
> CI: Added CLI to PR labelling config

- cli/Cargo.lock
- data-collector/Cargo.lock
- data-forwarder/Cargo.lock
- kiln_lib/Cargo.lock
- report-parser/Cargo.lock
- slack-connector/Cargo.lock
Updates cargo dependencies for all rust components
Brings in bug fixes for dependencies
> Meta: Chore update deps

- data-collector/Cargo.lock
- data-forwarder/Cargo.lock
- report-parser/Cargo.lock
- slack-connector/Cargo.lock
Updates the commit of Kiln_lib that other components depend on
Bring in Kiln_lib changes from #184 
> Update kiln lib dependencies in components

- kiln_lib/Cargo.lock
- kiln_lib/Cargo.toml
- kiln_lib/src/avro_schema.rs
- kiln_lib/src/dependency_event.rs
- kiln_lib/src/lib.rs
- kiln_lib/src/tool_report.rs
- kiln_lib/src/traits.rs
- kiln_lib/src/validation.rs
Adds an additional field to ToolReports to support suppressing issues, along with associated JSON, Avro and TOML serialising and parsing logic.
Required to build #83 
> [Kiln-lib] Finding Suppression

- data-collector/Cargo.lock
- data-collector/Cargo.toml
- data-collector/src/main.rs
- data-forwarder/Cargo.lock
- data-forwarder/Cargo.toml
- data-forwarder/src/main.rs
- report-parser/Cargo.lock
- report-parser/Cargo.toml
- report-parser/src/main.rs
- slack-connector/Cargo.lock
- slack-connector/Cargo.toml
- slack-connector/src/main.rs
- Adds finding suppression support to Kiln components
- Adds suppressed_issues field to kiln.toml (Documentation to be covered in #179)
- Closes #83 
- Closes #189 
> Finding suppression components

- report-parser/src/main.rs
- Build a reqwest client once at timeout and reuse it, instead of using a new client for every request
- Configure reqwest client with a 10 second timeout
- Reduce wasteful creation of reqwest clients for every reqwest and make use of keep-alive connection pooling
> Report-parser: Build a reqwest client once at startup

- report-parser/README.md
- slack-connector/README.md
- Updates docs to remove references to resolved issue #139 
- Documentation accuracy
> Docs: Update docs to remove references to resolved issue #139

- Makefile.toml
- Added additional useful targets to top level Makefile.toml
- Developer quality of life
> Meta: Improvements to top level Makefile.toml

- cli/src/main.rs
- data-collector/src/main.rs
- data-forwarder/src/main.rs
- kiln_lib/src/dependency_event.rs
- kiln_lib/src/kafka.rs
- kiln_lib/src/tool_report.rs
- kiln_lib/src/validation.rs
- report-parser/src/main.rs
- slack-connector/src/main.rs
- Applies Cargo fmt code style
- Fixes default Clippy lints
- Code consistency
- Approachability for new contributors
> Code cleanup

- Makefile.toml
- Adds missing Makefile.toml targets
- Fixes broken Makefile.toml
> Meta: Fixed top level makefile by adding missing targets

- cli/src/main.rs
- When running the kiln CLI, any old images for the tool being run will be deleted for you
Deletion logic is as follow:
* Any images for the current tool with no local tags will be deleted
* Any images without latest in their repo tags will be deleted (Ensures master-latest or the latest released images aren't deleted)
- It's important to not fill a machine with old docker images for a positive user experience
- Closes #145 
> CLI: Ensure old images for the tool being run are cleaned up

- .github/workflows/build-docker-images.yml
- Fix branch specifier for docker images CI workflow
- Fixes broken CI
> CI: Fix branch specifier broken by an overzealous find and replace

- docker-compose.yml
- Updates docker-compose.yml which is used for integration testing to use new docker image tags
- Works towards #217 
> Meta: Updated docker images tags in docker-compose.yml

- data-collector/src/main.rs
- Replaces master with main for branch names in tests
- Contributes to #217 
> Data-collector: Replace usage of master with main

- cli/src/main.rs
- Makes use of updated tool image docker tags
- Contributes to #217 
> CLI: Update tool docker image tags to replace master with git

- cli/src/main.rs
- Replaces static tool container naming with docker container naming and using the returned container ID in subsequent operations
- Allows a CI environment to run multiple instances of a tool concurrently
> CLI: Let docker name our tool containers so that multiple instances of each tool can run concurrently

- .github/workflows/continuous-integration-workflow.yml
- cli/src/main.rs
- data-forwarder/src/main.rs
- kiln_lib/src/dependency_event.rs
- kiln_lib/src/kafka.rs
- report-parser/src/main.rs
- Some linting and formatting fixes to multiple components
- Adding cargo format check and clippy linting to all components CI workflows
- Closes #150 
- Ensures consistent style and tidy code is merged to main
> Code style

- data-collector/src/main.rs
- Adds /health endpoint
- Useful for deployments behind a load balancer to check that the container is healthy
> Data-collector: Added Health endpoint that returns a 200 OK

- tool-images/ruby/bundler-audit/entrypoint.sh
- Fix invocation of mktemp in entrypoint script
- Add check for OFFLINE env var being undefined
- Fixes broken tool container
> Bundler-audit: Fix entrypoint.sh

- data-collector/Cargo.lock
- data-collector/Cargo.toml
- data-collector/src/lib.rs
- data-collector/src/main.rs
- Replaces the default actix_web logging middleware and the log crate with a custom slog based logging middleware that outputs logs in ECS format
- Provides logs that follow an existing schema in a structured format for easier processing
> Data-collector Elastic Common Schema logging

- install_dev_deps.sh
Updates the installer so that it now navigates between sub-directories in order to run cargo make without errors.
The installer errors out and doesn't work otherwise.
> bouncing between sub-directories for cargo make

- cli/src/main.rs
- Adds the ability for a user to specify a directory for the CLI to run a tool against, which defaults to the current directory if not provided
- The specific use case for this is using the Kiln CLI from inside a docker container. If the container running the Kiln CLI has the docker socket bind mounted into it, it will launch the tool container on the host, so the work directory will need to use the path on the docker host, not the path inside the calling container.
> CLI workdir option

- cli/src/main.rs
- Add KILN_SCAN_ENV env var to control what scan environment is provided to the tool container
- Makes it easier to run Kiln in a CI environment
- Closes #273 
> CLI: Add KILN_SCAN_ENV env var to control what scan environment is provided to the tool container

- cli/src/main.rs
- Change the behaviour of the CLI, so that if running a release build and the tool image required exists locally, don't repull it
- Images will still be pulled if they don't exist locally and --offline isn't supplier, or if running a debug build
- Helps minimise the impact of the recent Docker hub rate limits
- Contributes to #272 
> CLI: If running a release build and the tool image needed exists locally, don't repull it

- kiln_lib/src/log.rs
- Changes how logs are serialised to ECS compatible JSON. When serialising an Option<T>, if the Option is None, then do not emit anything to the serialised value
- Enabled components producing ECS logs to pass optional values to the formatter and have them be handled correctly, instead of trying to provide default values that might be meaningless or incompatible with ECS
> Kiln_lib: When serialising a value that is an Option::None, do not add a null value to the serialised value

- data-collector/Cargo.lock
- data-collector/src/lib.rs
- report-parser/Cargo.lock
- slack-connector/Cargo.lock
- Updates server component Kiln_lib dependencies to use the correct Option<T> handling for ECS log formatting
- Updates Data-collector to stop trying to provide defaults of '-' for values with type Option::None 
- Ensures we conform to ECS
> ECS format logs handle optional values correctly

- cli/src/main.rs
Updates the Kiln Cli to support Safety
Enables dependency checking of Python repos through the Cli
> Safety cli update

- .github/workflows/build-docker-images.yml
Allows building of Safety tool
To support Python dependency checking
> New job for building Safety docker image

- kiln_lib/Cargo.lock
- kiln_lib/Cargo.toml
- kiln_lib/src/dependency_event.rs
- kiln_lib/src/kafka.rs
- kiln_lib/src/tool_report.rs
- kiln_lib/src/validation.rs
Upgrades dependencies of Kiln_lib
Keeping dependencies up to date will allow us to adopt performance improvements, bug fixes and new features.
> Kiln lib dependencies update

- cli/Cargo.lock
- cli/Cargo.toml
- cli/src/main.rs
Updates dependencies for CLI
Keeping dependencies up to date will allow us to adopt performance improvements, bug fixes and new features.
> Cli dependencies update

- utils/Pipfile
- utils/Pipfile.lock
- utils/release.py
Adds a python script for performing the Kiln release process
The release process is quite long, has many steps and is easy to get wrong. This script will eliminate most of opportunities for human error and speed up the process
> Scripting release process

- kiln_lib/Cargo.lock
- kiln_lib/Cargo.toml
- kiln_lib/src/kafka.rs
Updates dependencies
Keeping Kiln dependencies up to date allows us to benefit from performance improvements, adopt new features and fix bugs.
> Kiln lib dependency updates
