simplybusiness/Kiln

Cargo.lock
kiln_lib/Cargo.toml
kiln_lib/README.md
kiln_lib/src/lib.rs

- Fixes the Avro schema for ToolReport by making tool_version field a Union of Null or String to represent that it is optional
- Adds Display Impls for all ToolReport fields
- Adds ToAvro impls for ToolReport
- Adds TryFrom impls for Avro Values to ToolReport fields
- Enabled converting between Avro and ToolReports with correct validation, which unlocks #37 

Kiln_lib types Avro Impls

---

kiln_lib/src/lib.rs

- Added From<DateTime<Utc>> impl for StartTime and EndTime
- Allows consuming code to create StartTime and EndTime types

kiln_lib: Added From<DateTime<Utc>> impl for StartTime and EndTime

---

data-collector/Cargo.lock
kiln_lib/Cargo.lock
kiln_lib/Cargo.toml
kiln_lib/src/lib.rs

- Removes the remaining serverless framework and lambda dependencies from Kiln_lib
- Works towards closing #47 

Remove remaining serverless from Kiln_lib

---

kiln_lib/Cargo.lock
kiln_lib/Cargo.toml
kiln_lib/src/lib.rs

- Expands the Avro round trip unit test to include going down to bytes to check schema matches ToolReport struct
- Switched to using the serde approach to Avro serialisation
- Corrected mistakes in ToolReport Avro schema around enums
- Fixes broken Avro serialisation

Kiln_lib: Fixed avro serialisation

---

kiln_lib/src/lib.rs

- Adds the `json_field_name` field to the ValidationError struct (type Option<String>)
- Updates calls to create ValidationError instances to add the appropriate value for new field
- Allows improved logging output in #62 

Kiln_lib: Added json_field_name field to ValidationError struct

---

.github/workflows/continuous-integration-workflow.yml

- Alters structure of CI jobs to collapse each component into a single job, rather, than separate jobs for build, test and lint
- Add steps for caching Cargo index, build cache etc between jobs, hashed on the Cargo.lock for each component
- Should reduce build time by not requiring dependencies to be rebuilt for every push to GitHub

CI: Cargo caching

---

kiln_lib/README.md
kiln_lib/src/lib.rs

Makes the git branch name optional
Allows us to gather git metadata when in detached head state

Kiln lib git branch name optional

---

kiln_lib/README.md
kiln_lib/src/lib.rs

Corrects a typo in Kiln_lib Avro schema to match casing of PlainText used elsewhere
Consistency throughout codebase 

Kiln_lib: Fix typo in Avro schema

---

tool-images/ruby/bundler-audit/Dockerfile

* Installs bundler 2 as part of image build
* Allows container to be used with codebases using bundler 1 or bundler 2.
* Fixed #86 

Tool: Fix bug #86 in Bundler Audit docker image to support Bundler 2.

---

.github/workflows/continuous-integration-workflow.yml
README.md
data-collector/Makefile.toml
tool-images/ruby/bundler-audit/Makefile.toml

- Updates the docker image naming format to make it clear which builds are from master and which are tagged releases
- Adds Makefile target for Data collector and bundler audit images for master and release builds
- Adds missing CI for Data-collector docker image
- Required for #44 

Meta: Update Makefiles to build and tag master and released docker images with clearer naming format

---

kiln_lib/Cargo.toml
kiln_lib/README.md
kiln_lib/src/lib.rs

- Adds the web, json and avro features to kiln_lib, so consuming crates can turn on only the features they need
- Reduces compilation times

Kiln_lib: Make parts of crate optional using features and conditional compilation

---

.github/workflows/continuous-integration-workflow.yml
Makefile.toml
data-collector/Cargo.toml
data-collector/Makefile.toml
data-forwarder/Makefile.toml
tool-images/ruby/bundler-audit/Makefile.toml

- Collapses component builds into a single job per component to avoid duplicating work
- Removes steps that aren't needed for CI
- Output caching between builds based on hash of Cargo.lock for each component
- Remove building of Docker images for CI, will only build on merge to master (future work)
- Introduce features and optional dependencies for Kiln_lib, so that consuming crates don't need to build code and dependencies they don't use
- Makes feedback on changes much quicker

CI speed up

---

.github/workflows/build-docker-images.yml

- Fixes the docker login step for building images on a merge to master
- Needed for #44

CI: Use a docker login step that actually exists

---

.github/workflows/build-docker-images.yml

- Changes the build target used for the data-forwarder binary when building docker images on master
- Fixes CI required for #44

CI: Fix build target for data-forwarder when building docker images on master

---

.github/workflows/build-docker-images.yml

- Updates build cache key for master musl builds
- To prevent cache clobbering for regular builds

CI: Change build cache keys for libc-musl builds so they don't clobber cache for regular builds

---

.github/workflows/build-docker-images.yml

#What does this PR change?
- Adds working directories in master push CI
- Fixes build needed for #44

CI: Add missing working-directory directives to build-docker-image CI so build targets can be found

---

.github/workflows/build-docker-images.yml
data-collector/Makefile.toml

- Switches the master push docker image build workflow to use the data-collector build target that tags images as being built from master
- Fixes docker image builds on master

CI: Fix docker image build for data-collector when pushing to master

---

tool-images/ruby/bundler-audit/entrypoint.sh

- Update entrypoint script to cleanup tool output text file after it is not needed
- Fixes #106 

Bundler-audit: Update entrypoint script to cleanup tool output text file after it is not needed, fixed #106.

---

data-collector/Cargo.lock
data-collector/docs/request-response.md
data-collector/src/main.rs
data-forwarder/Cargo.lock
data-forwarder/Cargo.toml
data-forwarder/src/main.rs

- Adopts changes from kiln_lib that add an event_version field and event_id field to tool reports
- Allows us to trace a derived event to it's parent
- Allows us to evolve the schema of ToolReports over time

Adopt event schema changes

---

tool-images/ruby/bundler-audit/Dockerfile

- Updated Bundler-audit Dockerfile to install both major versions of Bundler gem
- Compatibility with both old and new versions of Bundler used by projects

Bundler-audit: Ensured that container now have both bundler 1.17.3 and bundler 2

---

docs/release-process.md

#What does this PR change?
- Updates release docs to remove Windows build step
- Updates release docs to include artifact signing for CLI app and repo tarball
- Keeps documentation up to date with plans in #44 

Docs: Update release docs to remove windows binary build and include artifact signing

---

docker-compose.yml
docs/integration_testing.md

- Updated docker-compose.yml to use new image naming format
- Updated integration testing docs to use new image naming format
- Updated integration testing docs to use valid payload with new fields
- Fixes broken integration testing stack script
- Resolves inconsistencies in documentation

Fix references to old naming convention

---

kiln_lib/src/tool_report.rs

- Ensures that the `use failure::err_msg;` statement has the correct cfg feature attribute applied
- Fixes the build when building kiln_lib without the avro feature enabled

Kiln_lib: Correctly applied cfg feature attribute to failure::err_msg use statement

---

kiln_lib/src/tool_report.rs

- Adds PartialEq impls for ToolName and OutputFormat
- Adds a TryFrom<&str> impl for OutputFormat to make comparisons less syntactically noisy

Newtype partial eq impls

---

kiln_lib/src/tool_report.rs

- Makes the PartialEq impl for ToolName work with &str

Kiln_lib: Updated PartialEq<&str> impl for ToolName so it works as expected

---

kiln_lib/src/tool_report.rs

- Makes the PartialEq impl for OutputFormat work with &str

Kiln_lib: Updated PartialEq<&str> impl for OutputFormat so it works as expected

---

kiln_lib/src/tool_report.rs

- Adds an AsRef<str> impl to the ToolOutput newtype to allow the report-parser to immutably borrow the raw tool output for parsing

Kiln_lib: Added AsRef<str> impl to ToolOutput

---

kiln_lib/src/kafka.rs

- Makes KafkaBootstrapTlsConfig impl Clone trait
- Allows a config to be reused when a caller needs to setup multiple consumers or producers for Kafka

Kiln_lib: Added derived Clone impl to KafkaBootstrapTlsConfig

---

kiln_lib/src/avro_schema.rs
kiln_lib/src/dependency_event.rs
kiln_lib/src/validation.rs

- Adds the CVSS field to DependencyEvent, which covers the version as well as the score (which may be unknown)
- Adds associated Avro parsing logic

Kiln_lib: Added CVSS to DependencyEvent struct

---

report-parser/Cargo.lock
report-parser/Cargo.toml
report-parser/src/main.rs

- Downloads CVE data from NIST NVD data feeds and parses it into a hashmap
- Adds regular polling of the latest modified META file per NVD recommendations to check for updates (https://nvd.nist.gov/vuln/data-feeds)
- Tries to add the CVSS V3 score to a dependency event, falling back to V2, falling back to unknown
- Allows users to prioritise dependency fixes based on the severity of the vulnerability

Dependency event cvss enrichment

---

kiln_lib/src/dependency_event.rs

- Adds Display Impls to the Cvss Struct and CvssVersion enum
- Needed to be able to include severity in slack-connector (#18)

Kiln_lib: Added Display Impls for Cvss and CvssVersion

---

README.md

- Updates minimum supported rust version in README
One of our dependencies now requires a more recent version of Rust than 1.37, so we have updated this to the current latest stable release

Docs: Update project readme to state minimum supported rust version is 1.40

---

.github/ISSUE_TEMPLATE/tech_debt.md

- Adds an issue template to capture tech debt
- Allows project maintainers to collect consistent information about technical debt issues

Meta: Added tech debt issue template

---

report-parser/src/main.rs

- Downloads the NIST NVD 2020 date file on startup
- Ensures report-parser component has an up-to-date collection of vulnerability information

Report-parser: Download NIST NVD 2020 date file on startup

---

data-forwarder/Cargo.lock
data-forwarder/Cargo.toml
data-forwarder/src/main.rs
tool-images/ruby/bundler-audit/Dockerfile

- Updated data-forwarder to use openssl-probe to find system CA certificate bundle
- Installs the ca-certificates Alpine package in Docker image for bundler-audit
- Allows sensitive information about project security issues to be sent over TLS

Add TLS support to Bundler-audit tool image

---

data-collector/Cargo.lock
data-collector/Cargo.toml
data-collector/Dockerfile
data-collector/Makefile.toml
data-collector/entrypoint.sh
data-collector/src/main.rs
data-forwarder/Cargo.lock
data-forwarder/Makefile.toml
docker-compose.yml
report-parser/Cargo.lock
report-parser/Cargo.toml
report-parser/Makefile.toml
report-parser/src/main.rs
slack-connector/Cargo.lock
slack-connector/Cargo.toml
slack-connector/Makefile.toml
slack-connector/src/main.rs

- Makes use of rust-rdkafka crate, via kiln_lib
- Fixes #139 

Use rdkafka in consuming components

---

cli/Cargo.lock
cli/Cargo.toml
cli/src/main.rs

- Makes the docker repo, image and tag used for a tool configurable at the CLI
- Closes #107 
- Makes testing specific tool images much easier

CLI: Make docker image configurable for tool

---

cli/README.md

Adds documentation for the Kiln CLI binary.
- Makes it easier for new Kiln users to use the CLI
- Closes #179 

CLI: Add README.md covering building and configuring the CLI

---

report-parser/README.md

Documents the NVD_BASE_URL environment variable that the can be used to make the Report-parser download NVD data from an alternative location.
- Closes #142 
- Makes it easier to do Kiln development without hammering NIST's NVD servers with requests

Report-parser: Document the NVD_BASE_URL environment variable

---

data-collector/README.md

- Updates documentation to reflect changes to how CA certs are provided to data-collector container, which closes #130 
- Documentation accuracy

Data-collector: Update documentation for providing TLS certificates to container

---

slack-connector/Cargo.lock
slack-connector/Cargo.toml
slack-connector/src/main.rs

* Ensures that slack messages are not sent more often than 1 per second for each replica of the Slack Connector
* Switches to a stream pipeline approach to consuming and dispatching events, to decouple these processes
* Adds retry logic for Slack messages that couldn't be sent
* Adds a backoff timer for Slack API requests that return a rate limited response, respecting the Retry-After header value, defaulting to 30 seconds if one isn't provided
* To be good citizens and respectful of Slack's documented API rate limits (and to avoid having the Slack Connector banned by Slack!)
* Closes #143 

Respect slack api limits

---

cli/Makefile.toml

- Ensures that RPMs that are built include the architecture that they're built for
- End user clarity

CLI: Fix RPM file naming by appending arch to name

---

cli/src/main.rs

- Renames the use-local-image CLI switch to a more general offline switch
- Passes an OFFLINE env var to tool containers
- Allows tool scans to occur without network access

Cli offline switch

---

tool-images/ruby/bundler-audit/entrypoint.sh

- Adds check for offline flag and will not update bundler-audit DB if flag set
- Enables offline scanning

Ruby-dependencies: Enable offline scanning

---

data-forwarder/Cargo.lock
data-forwarder/Cargo.toml
data-forwarder/src/main.rs

- Adds retry logic to Data-forwarder to increase resilience to transient network issues (uses Fibonacci backoff strategy starting at 1 second, makes 5 retries after initial attempt)
- Makes it more likely that data will be successfully submitted to Kiln

Data-forwarder: Added retry logic to data-forwarder

---

.github/workflows/build-docker-images.yml
data-collector/Makefile.toml
report-parser/Makefile.toml
slack-connector/Makefile.toml
tool-images/ruby/bundler-audit/Makefile.toml

- Updates the names used in docker images to indicate they're from the git repo default branch to use `git`
- Because there's no reason to use a term of oppression

Remove master terminology from docker image names

---

docs/data-analysis/repo-analyser/repo-analyser.py

- Fixed how repo_analyser.py calls kiln-cli
- Fixed use of non-existent variable when printing error message
- Working documentation

Docs: Update repo analyser script in data analysis docs to use offline flag when calling Kiln CLI

---

data-collector/Dockerfile
report-parser/Dockerfile
slack-connector/Dockerfile
tool-images/ruby/bundler-audit/Dockerfile

- Parameterises the base images used when building docker images, defaulting the the previously hard coded base images
- Allows users to customise the base image used, if they need to use an internal hardened image when deploying Kiln

Parameterise base images

---

tool-images/ruby/bundler-audit/Makefile.toml

- Update bundler-audit tool makefile to ensure data-forwarder binary has been copied to correct location before building
- Makes sure top level `cargo make tools` is using the fresh data-forwarder binary

Bundler-audit: Add dependency to docker build target

---

data-collector/Dockerfile
data-collector/entrypoint.sh
report-parser/Dockerfile
report-parser/entrypoint.sh
slack-connector/Dockerfile
slack-connector/entrypoint.sh

- Switches from su-exec to gosu for dropping privileges in container entrypoint
- su-exec is only easily available on Alpine. This change makes it easier for other base images to be used without having to change the entrypoint script, although the usage of the apk tool in the Dockerfile will require writing a custom Dockerfile if a non-alpine base image is used

Replace suexec with gosu

---

data-collector/entrypoint.sh
report-parser/entrypoint.sh
slack-connector/entrypoint.sh

- Updates container entrypoint scripts to check if tls directory exists and isn't empty before trying to copy the certificates to the system trust store
- Reduces error messages when users aren't supplying additional TLS certificates to components

Test for cert in entrypoint

---

data-collector/Cargo.lock
data-collector/entrypoint.sh
data-collector/src/main.rs
report-parser/Cargo.lock
report-parser/entrypoint.sh
report-parser/src/main.rs
slack-connector/Cargo.lock
slack-connector/entrypoint.sh
slack-connector/src/main.rs

- Updates server components to use kiln_lib trust store probing
- Updates server components entrypoint scripts to ensure both alpine trust stores are updated with certs
- Makes server components more portable between distros

Trust store probe components

---

README.md

- Adds suggestions for ways to contribute to Kiln that don't involve writing Rust
- Closes #54 
- Encourages participation from people who aren't comfortable with Rust and in areas of the project people might not think to contribute to

Docs: Added additional contribution suggestions to README.md

---

data-collector/Dockerfile
report-parser/Dockerfile
slack-connector/Dockerfile

- Occasionally during docker image builds, the build will fail while cleaning up the gnupg directory created during gosu installation (Example: https://github.com/simplybusiness/Kiln/runs/793283512?check_suite_focus=true). This PR fixes that.
- Build stability

Fix docker build random failure

---

data-collector/Cargo.lock

- Upgrades version of actix-rt  crate used from 1.1.0 to 1.1.1 in data-collector
- 1.1.0 of actix-rt was yanked because of a memory leak, where memory usage scales with cumulative requests (https://github.com/actix/actix-net/issues/129)

Data-collector: Upgraded Actix-rt to 1.1.1 to try and resolve memory leak

---

tool-images/ruby/bundler-audit/entrypoint.sh

- Ensure we're using a unique filename to temporarily store tool output when running bundler audit
- Allows one host to run multiple concurrent instances of bundler audit through Kiln without running into data races with tool-output.txt

Bundler-audit: Use unique file name in bundler-audit tool run

---

kiln_lib/src/validation.rs

- Adds an impl of the actix_web::ResponseError trait for ValidationErrors behind the web feature
Simplifies error handling in DataCollector by allowing us to return a ValidationError from the handler directly, instead of having to wrap it in a failure struct to return something implementing that trait

Kiln_lib: Add impl of ResponseError for ValidationErrors

---

data-collector/Cargo.lock
data-collector/Cargo.toml
data-collector/src/lib.rs

* Adds event.id to log output to uniquely identify a log line
* Adds transaction.id to log output to group log lines for a specific request together
* Adds transaction id to request extensions for further logging if needed
Note: Event and Transaction IDs are UUIDv4 formatted as hyphenated, lower hex encoded strings
* Enables easier debugging of issues and gives operators the ability to uniquely identify logs

Data-collector: Tracing fields

---

docker-compose.yml
report-parser/Cargo.lock
report-parser/Cargo.toml
report-parser/src/main.rs

- Adds ECS compatible log output for the Report-parser
- Allows for easier processing and parsing of log output for Kiln operators
- Part of #247 

Report-parser ECS Logging

---

slack-connector/Cargo.lock
slack-connector/Cargo.toml
slack-connector/src/main.rs

- Adds ECS compatible logging to the Slack Connector
- Part of #247 
- Makes it easier for Kiln operators to parse and process logs using a structured format and a common schema

Slack-connector: Added ECS compatible logging

---

README.md
cli/src/main.rs
tool-images/ruby/bundler-audit/Dockerfile
tool-images/ruby/bundler-audit/Makefile.toml

- Updates project README to use new simplified docker image versioning scheme
- Removes tool version number from bundler-audit images
- Updates CLI to use git-latest tag for tool images by default when built in debug mode, otherwise it uses a tag with the same version number as the CLI binary
- Prevents Kiln users from using new tool images with possible breaking changes in them

Image versioning

---

cli/Cargo.lock
cli/Cargo.toml
cli/src/main.rs

- Fixes an issue in CLI when you're running in a container and use the `--work-dir` flag to override the directory that a tool should run in, where the CLI will attempt to use the same path for reading the kiln.toml file, which won't exist inside the container the CLI is running in. We fix this by identifying if we're running in a container by inspecting procfs to find the cgroup our current process belongs to and checking if the cgroup path begins with `/docker/<someid>`. If it does, the trailing component of the cgroup path is the id of the container we're running in. We then inspect the mounts for that container ID and check if the source of any of those mounts is the path the CLI has been told to scan. If so, we return the target of that mount as the path to read kiln.toml from inside …

Container path mapping

---

cli/Cargo.lock
cli/Cargo.toml
cli/src/main.rs

- Upgrades the version of the Bollard crate used by the CLI to 0.8.0
This PR fixes as issue that occurs when running Kiln-cli inside a Docker container where ulimits are set. In this situation, Kiln-cli is unable to inspect the container it is running in, leaving it unable to determine if the directory it has been instructed to scan with the `--work-dir` option is the source of a mount into this container, and map it appropriately.
This manifests itself as exiting with an error saying that kiln.toml does not exist, which is incorrect.
The root cause of this issue was using an old version of the Bollard crate to interact with the Docker API, which caused the JSON response from the inspect container API to fail to deserialize from JSON when the `ulimits` field is not null. This was fixed in …

CLI: Fix bug in work-dir path mapping when running in a container

---

kiln_lib/Cargo.lock
kiln_lib/Cargo.toml
kiln_lib/src/lib.rs
kiln_lib/src/log.rs

- Adds a new "log" feature to Kiln_lib to make Slog and json_dotpath dependencies optional
- Adds the NestedJsonFmt Slog drain which builds nested JSON objects from log records that use JSON dotpath keys
- Allows us to fix the log output from components to make it compatible with Elastic Common Schema without requiring the use of the computationally expensive de-dot Logstash plugin

Build Slog Drain that builds nested JSON objects from KV pairs that use json dotpath keys 

---

data-collector/Cargo.lock
data-collector/Cargo.toml
data-collector/src/main.rs
report-parser/Cargo.lock
report-parser/Cargo.toml
report-parser/src/main.rs
slack-connector/Cargo.lock
slack-connector/Cargo.toml
slack-connector/src/main.rs

- Changes the Log drain used by the Data-collector, Report-parser and Slack-connector to use the NestedJsonFmt Drain from Kiln_lib to correctly format logs to be ECS compatible
- Avoids needing a logstash configuration that uses the computationally expensive de-dot filter

Fix Log Format

---

kiln_lib/Cargo.lock

- Fixed format of kiln_lib cargo.lock by running `cargo build --all-features`
- Prevents this change reoccuring in unrelated changes

Kiln_lib: Fix Cargo.lock format

---

.github/workflows/continuous-integration-workflow.yml
cli/Cargo.lock
cli/Cargo.toml
cli/README.md
cli/src/main.rs

- CLI can now pull tool images from custom registries specified using the KILN_DOCKER_REGISTRY environment variable
- CLI can now provide credentials to Docker Image registry using KILN_DOCKER_USERNAME and KILN_DOCKER_PASSWORD environment variables
- Adds support for private Docker image registries
- Helps work around the rate limits imposed by Docker Hub (#272)
The CLI is starting to get quite big for one file, I don't want to delay this feature by refactoring now, but we will need to start refactoring these components to split them into multiple files for easy of navigation. These modularisation refactors can also be used to introduce further tests.

Private registries and credentials

---

report-parser/src/main.rs

- Ensures that the report parser will fetch data from the NIST NVD after 2020
- To maintain an up to date cache of vulnerability data

Report-parser: Replace hardcoded year for data range with current year when pulling NIST NVD data

---

data-collector/src/lib.rs

- Ensures that Data-collector ECS format logs conform to the format. Previously, Source.IP was including the source port, which is not compliant
- Correct logging output

Fix data collector log source ip

---

Makefile.toml
cli/Makefile.toml
data-collector/Makefile.toml
data-forwarder/Makefile.toml
report-parser/Makefile.toml
slack-connector/Makefile.toml

- Switch to using latest stable docker image for musl builds instead of the old stable-openssl11 tag
- Fix makefile targets in top-level makefile
- Tracking latest stable Rust and linking against current releases of OpenSSL

Use latest stable musl builder image

---

.github/workflows/build-docker-images.yml
data-collector/Makefile.toml
data-forwarder/Makefile.toml
report-parser/Makefile.toml
slack-connector/Makefile.toml

- Uses filesystem paths instead of docker volumes for build caching
- Updates Github Actions docker image build workflow to use new cache paths
- Sets env var for CARGO_HOME to point to /opt/rust/cargo, which is the new location of cargo in the stable tagged musl builder images
- Greatly improved build times on cache hit

Meta: Makefile.toml changes needed to correctly support build caching with stable tag for musl builder docker image

---

Makefile.toml
report-parser/Cargo.lock
report-parser/Cargo.toml
report-parser/src/main.rs
tool-images/python/safety/Dockerfile
tool-images/python/safety/Makefile.toml
tool-images/python/safety/entrypoint.sh

It introduces support for the python Safety dependency checker into report parser.
Python projects can be checked for dependencies on vulnerable packages.

Python safety

---

kiln_lib/Cargo.lock
kiln_lib/Cargo.toml
kiln_lib/src/kafka.rs

Improves error handling in Kafka module of Kiln_lib so that consumers are working with an error enum that impl's the std::error::Error trait
Makes error handling clearer and more ergonomic in consuming code and allows us to use the anyhow crate

Kiln lib kafka thiserror

---

data-collector/Cargo.lock
data-collector/Cargo.toml
data-collector/src/lib.rs
data-collector/src/main.rs

* Updates dependencies in Data-collector, including Actix_web (which should resolve #240), Tokio and rdkafka
* Replaces failure crate with anyhow and thiserror
Keeping Kiln dependencies up to date allows us to adopt new features, fix bugs and benefit from any performance improvements

Data collector dependencies update

---

report-parser/Cargo.lock
report-parser/Cargo.toml
report-parser/src/main.rs

* Updates dependencies in Report-parser, including rdkafka, avro_rs & Tokio
* Replaces failure with anyhow and thiserror
Keeping Kiln dependencies up to date allows us to adopt new features, fix bugs and benefit from performance improvements

Report parser dependencies update

---

slack-connector/Cargo.lock
slack-connector/Cargo.toml
slack-connector/src/main.rs

* Updates dependencies in Slack-connector including rdkafka, tokio & avro_rs
* Replaces failure with anyhow and thiserror
Keeping Kiln dependencies up to date allows us to adopt new features, fix bugs and benefit from performance improvements

Slack connector dependencies update

---

data-collector/Cargo.lock

Updates actix_web and related dependencies in data-collector
Keeping Kiln dependencies up to date allows us to benefit from performance improvements, adopt new features and fix bugs

Data-collector: Upgrade actix_web and related dependencies

---

kiln_lib/Cargo.lock
kiln_lib/Cargo.toml

- Updates kiln_lib to use latest beta of actix_web
- Keeping Kiln dependencies up to date allows us to benefit from performance improvements, adopt new features and benefit from bug fixes

Kiln_lib: Update actix_web dependency

---

data-collector/Cargo.lock
data-collector/Cargo.toml

- Updates data-collector to use latest beta of actix_web
- Keeping Kiln dependencies up to date allows us to benefit from performance improvements, adopt new features and benefit from bug fixes

Data collector actix update

---

cli/Cargo.lock
data-collector/Cargo.lock
data-collector/Cargo.toml
data-forwarder/Cargo.lock
report-parser/Cargo.lock
report-parser/Cargo.toml
slack-connector/Cargo.lock
slack-connector/Cargo.toml

Updates dependencies in all Kiln components
Since enabling dependabot there were a lot of transitive dependency updates PRs. Dependabot config has changed to only update direct dependencies, this PR should clear up all of the transitive dependency update PRs

Dependency updates

---

data-collector/src/lib.rs

- Fixes a bug in the Data-Collector that was causing the request logger to consume message bodies, resulting in all requests returning an error that the request body was empty
- Fixes a show-stopper bug for next release

Data collector missing request body fix

---

data-forwarder/src/main.rs

Ensures that the branch name gets populated even in detached head state
Important to know what branch of a project was scanned using one of the kiln supported tools

Data-forwarder: Detect branch name even when in detached head state

---

kiln_lib/Cargo.lock
kiln_lib/Cargo.toml
kiln_lib/src/validation.rs

Brings kiln_lib up to the latest beta for Actix_web
Keeping Kiln's dependencies up to date allows us to benefit from new features, bug fixes and performance improvements

Kiln_lib: Upgrade Actix-web to latest beta

---

data-collector/Cargo.lock
data-collector/Cargo.toml

Brings  Data-collector up to the latest Actix_web beta
Keeping Kiln's dependencies up to date allows us to benefit from new features, bug fixes and performance improvements

Data-collector: Upgrade actix_web to latest beta

---

cli/Cargo.lock
cli/Cargo.toml
cli/src/main.rs

Updates the indicatif dependency in the CLI, which is used  for displaying progress  bars
Keeping Kiln's dependencies up to date allows us to adopt new features, benefit from performance improvements and fix bugs.

CLI: Update indicatif dependency

---

data-collector/src/lib.rs

Fixes a bug in data collector logging
Because currently the Data-Collector logs a request path where it should be logging a request method

Data-collector: Fix bug that causes request path to be logged in the http.request.method field

---

data-collector/README.md
docker-compose.yml
docs/quickstart/README.md
kiln_lib/src/kafka.rs

Increases the default message size limits in Kafka to allow for larger ToolReports
Yarn-audit (and other tools) that return large ToolReports can be handled

Support large kafka messages
